"""easystock init

Revision ID: b3fd9f86cbb5
Revises: 
Create Date: 2026-02-14 17:57:06.113614

"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'b3fd9f86cbb5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('businesses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('tax_rate', sa.Float(), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('subscription_tier', sa.String(length=50), nullable=True),
    sa.Column('subscription_expiry', sa.DateTime(), nullable=True),
    sa.Column('max_users', sa.Integer(), nullable=True),
    sa.Column('max_stores', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('idx_business_created', 'businesses', ['created_at'], unique=False)
    op.create_index('idx_business_email', 'businesses', ['email'], unique=False)
    op.create_table('categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'name', name='unique_category_name_per_business')
    )
    op.create_index('idx_category_business', 'categories', ['business_id'], unique=False)
    op.create_index('idx_category_parent', 'categories', ['parent_id'], unique=False)
    op.create_table('stores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('location', sa.String(length=500), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('manager_name', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('opening_time', sa.String(length=10), nullable=True),
    sa.Column('closing_time', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_store_business', 'stores', ['business_id'], unique=False)
    op.create_index('idx_store_name', 'stores', ['name'], unique=False)
    op.create_table('suppliers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('contact_person', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('alternate_phone', sa.String(length=50), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('tax_id', sa.String(length=100), nullable=True),
    sa.Column('payment_terms', sa.String(length=200), nullable=True),
    sa.Column('website', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'email', name='unique_supplier_email')
    )
    op.create_index('idx_supplier_business', 'suppliers', ['business_id'], unique=False)
    op.create_index('idx_supplier_name', 'suppliers', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'MANAGER', 'STAFF', name='userrole'), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=True),
    sa.Column('verification_token', sa.String(length=200), nullable=True),
    sa.Column('reset_password_token', sa.String(length=200), nullable=True),
    sa.Column('reset_password_expires', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('idx_user_business', 'users', ['business_id'], unique=False)
    op.create_index('idx_user_email', 'users', ['email'], unique=False)
    op.create_index('idx_user_role', 'users', ['role'], unique=False)
    op.create_table('inventory_counts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('store_id', sa.UUID(), nullable=False),
    sa.Column('counted_by', sa.UUID(), nullable=True),
    sa.Column('count_number', sa.String(length=100), nullable=True),
    sa.Column('count_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['counted_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('count_number')
    )
    op.create_index('idx_inv_count_business', 'inventory_counts', ['business_id'], unique=False)
    op.create_index('idx_inv_count_number', 'inventory_counts', ['count_number'], unique=False)
    op.create_index('idx_inv_count_store', 'inventory_counts', ['store_id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('store_id', sa.UUID(), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('supplier_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('barcode', sa.String(length=100), nullable=True),
    sa.Column('qr_code', sa.String(length=500), nullable=True),
    sa.Column('cost_price', sa.Float(), nullable=False),
    sa.Column('selling_price', sa.Float(), nullable=False),
    sa.Column('wholesale_price', sa.Float(), nullable=True),
    sa.Column('discount_price', sa.Float(), nullable=True),
    sa.Column('tax_rate', sa.Float(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('reserved_quantity', sa.Integer(), nullable=True),
    sa.Column('available_quantity', sa.Integer(), nullable=True),
    sa.Column('low_stock_threshold', sa.Integer(), nullable=True),
    sa.Column('reorder_point', sa.Integer(), nullable=True),
    sa.Column('maximum_stock_level', sa.Integer(), nullable=True),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('size', sa.String(length=50), nullable=True),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('weight_unit', sa.String(length=10), nullable=True),
    sa.Column('expiry_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('manufacture_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('image_urls', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('IN_STOCK', 'LOW_STOCK', 'OUT_OF_STOCK', 'OVERSTOCK', name='stockstatus'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('is_taxable', sa.Boolean(), nullable=True),
    sa.Column('is_digital', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('predicted_daily_demand', sa.Float(), nullable=True),
    sa.Column('predicted_reorder_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('seasonality_factor', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('barcode'),
    sa.UniqueConstraint('business_id', 'sku', name='unique_product_sku_per_business')
    )
    op.create_index('idx_product_barcode', 'products', ['barcode'], unique=False)
    op.create_index('idx_product_business', 'products', ['business_id'], unique=False)
    op.create_index('idx_product_category', 'products', ['category_id'], unique=False)
    op.create_index('idx_product_expiry', 'products', ['expiry_date'], unique=False)
    op.create_index('idx_product_sku', 'products', ['sku'], unique=False)
    op.create_index('idx_product_status', 'products', ['status'], unique=False)
    op.create_index('idx_product_store', 'products', ['store_id'], unique=False)
    op.create_table('purchase_orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('po_number', sa.String(length=100), nullable=False),
    sa.Column('order_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expected_delivery_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('subtotal', sa.Float(), nullable=True),
    sa.Column('tax_amount', sa.Float(), nullable=True),
    sa.Column('shipping_cost', sa.Float(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('terms', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('po_number')
    )
    op.create_index('idx_po_business', 'purchase_orders', ['business_id'], unique=False)
    op.create_index('idx_po_number', 'purchase_orders', ['po_number'], unique=False)
    op.create_index('idx_po_status', 'purchase_orders', ['status'], unique=False)
    op.create_index('idx_po_supplier', 'purchase_orders', ['supplier_id'], unique=False)
    op.create_table('sales',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('store_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('invoice_number', sa.String(length=100), nullable=False),
    sa.Column('sale_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('customer_name', sa.String(length=200), nullable=True),
    sa.Column('customer_email', sa.String(length=200), nullable=True),
    sa.Column('customer_phone', sa.String(length=50), nullable=True),
    sa.Column('customer_address', sa.Text(), nullable=True),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('tax_amount', sa.Float(), nullable=True),
    sa.Column('discount_amount', sa.Float(), nullable=True),
    sa.Column('discount_type', sa.String(length=20), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('paid_amount', sa.Float(), nullable=True),
    sa.Column('change_amount', sa.Float(), nullable=True),
    sa.Column('payment_method', sa.Enum('CASH', 'MOBILE', 'BANK', 'CARD', name='paymentmethod'), nullable=False),
    sa.Column('payment_status', sa.String(length=50), nullable=True),
    sa.Column('transaction_id', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_number')
    )
    op.create_index('idx_sale_business', 'sales', ['business_id'], unique=False)
    op.create_index('idx_sale_customer', 'sales', ['customer_email', 'customer_phone'], unique=False)
    op.create_index('idx_sale_date', 'sales', ['sale_date'], unique=False)
    op.create_index('idx_sale_invoice', 'sales', ['invoice_number'], unique=False)
    op.create_index('idx_sale_payment', 'sales', ['payment_method', 'payment_status'], unique=False)
    op.create_index('idx_sale_store', 'sales', ['store_id'], unique=False)
    op.create_table('user_stores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('store_id', sa.UUID(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'store_id', name='unique_user_store')
    )
    op.create_index('idx_user_store_store', 'user_stores', ['store_id'], unique=False)
    op.create_index('idx_user_store_user', 'user_stores', ['user_id'], unique=False)
    op.create_table('inventory_count_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('inventory_count_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('expected_quantity', sa.Integer(), nullable=False),
    sa.Column('counted_quantity', sa.Integer(), nullable=False),
    sa.Column('variance', sa.Integer(), nullable=False),
    sa.Column('variance_reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['inventory_count_id'], ['inventory_counts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_inv_count_item_count', 'inventory_count_items', ['inventory_count_id'], unique=False)
    op.create_index('idx_inv_count_item_product', 'inventory_count_items', ['product_id'], unique=False)
    op.create_table('price_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('old_cost_price', sa.Float(), nullable=True),
    sa.Column('new_cost_price', sa.Float(), nullable=True),
    sa.Column('old_selling_price', sa.Float(), nullable=True),
    sa.Column('new_selling_price', sa.Float(), nullable=True),
    sa.Column('changed_by', sa.UUID(), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_price_history_created', 'price_history', ['created_at'], unique=False)
    op.create_index('idx_price_history_product', 'price_history', ['product_id'], unique=False)
    op.create_table('purchase_order_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('purchase_order_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('quantity_ordered', sa.Integer(), nullable=False),
    sa.Column('quantity_received', sa.Integer(), nullable=True),
    sa.Column('unit_cost', sa.Float(), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_po_item_po', 'purchase_order_items', ['purchase_order_id'], unique=False)
    op.create_index('idx_po_item_product', 'purchase_order_items', ['product_id'], unique=False)
    op.create_table('purchase_receipts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('purchase_order_id', sa.UUID(), nullable=False),
    sa.Column('received_by', sa.UUID(), nullable=True),
    sa.Column('receipt_number', sa.String(length=100), nullable=True),
    sa.Column('received_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['received_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('receipt_number')
    )
    op.create_index('idx_receipt_number', 'purchase_receipts', ['receipt_number'], unique=False)
    op.create_index('idx_receipt_po', 'purchase_receipts', ['purchase_order_id'], unique=False)
    op.create_table('reorder_suggestions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('suggested_quantity', sa.Integer(), nullable=False),
    sa.Column('current_stock', sa.Integer(), nullable=False),
    sa.Column('days_until_stockout', sa.Integer(), nullable=True),
    sa.Column('reorder_by_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('acted_upon_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_reorder_business', 'reorder_suggestions', ['business_id'], unique=False)
    op.create_index('idx_reorder_priority', 'reorder_suggestions', ['priority'], unique=False)
    op.create_index('idx_reorder_product', 'reorder_suggestions', ['product_id'], unique=False)
    op.create_index('idx_reorder_status', 'reorder_suggestions', ['status'], unique=False)
    op.create_table('sale_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sale_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('sold_by', sa.UUID(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('cost_price', sa.Float(), nullable=False),
    sa.Column('discount_amount', sa.Float(), nullable=True),
    sa.Column('tax_amount', sa.Float(), nullable=True),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sold_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sale_item_product', 'sale_items', ['product_id'], unique=False)
    op.create_index('idx_sale_item_sale', 'sale_items', ['sale_id'], unique=False)
    op.create_table('sales_predictions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('prediction_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('predicted_quantity', sa.Float(), nullable=False),
    sa.Column('confidence_lower', sa.Float(), nullable=True),
    sa.Column('confidence_upper', sa.Float(), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('features_used', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'prediction_date', name='unique_product_prediction_date')
    )
    op.create_index('idx_prediction_business', 'sales_predictions', ['business_id'], unique=False)
    op.create_index('idx_prediction_date', 'sales_predictions', ['prediction_date'], unique=False)
    op.create_index('idx_prediction_product', 'sales_predictions', ['product_id'], unique=False)
    op.create_table('stock_movements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('movement_type', sa.Enum('IN', 'OUT', 'ADJUSTMENT', 'RETURN', name='movementtype'), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('previous_quantity', sa.Integer(), nullable=False),
    sa.Column('new_quantity', sa.Integer(), nullable=False),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('reference_id', sa.UUID(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_stock_movement_business', 'stock_movements', ['business_id'], unique=False)
    op.create_index('idx_stock_movement_created', 'stock_movements', ['created_at'], unique=False)
    op.create_index('idx_stock_movement_product', 'stock_movements', ['product_id'], unique=False)
    op.create_index('idx_stock_movement_reference', 'stock_movements', ['reference_type', 'reference_id'], unique=False)
    op.create_index('idx_stock_movement_type', 'stock_movements', ['movement_type'], unique=False)
    op.create_table('purchase_receipt_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('receipt_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('quantity_received', sa.Integer(), nullable=False),
    sa.Column('unit_cost', sa.Float(), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['receipt_id'], ['purchase_receipts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_receipt_item_product', 'purchase_receipt_items', ['product_id'], unique=False)
    op.create_index('idx_receipt_item_receipt', 'purchase_receipt_items', ['receipt_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_receipt_item_receipt', table_name='purchase_receipt_items')
    op.drop_index('idx_receipt_item_product', table_name='purchase_receipt_items')
    op.drop_table('purchase_receipt_items')
    op.drop_index('idx_stock_movement_type', table_name='stock_movements')
    op.drop_index('idx_stock_movement_reference', table_name='stock_movements')
    op.drop_index('idx_stock_movement_product', table_name='stock_movements')
    op.drop_index('idx_stock_movement_created', table_name='stock_movements')
    op.drop_index('idx_stock_movement_business', table_name='stock_movements')
    op.drop_table('stock_movements')
    op.drop_index('idx_prediction_product', table_name='sales_predictions')
    op.drop_index('idx_prediction_date', table_name='sales_predictions')
    op.drop_index('idx_prediction_business', table_name='sales_predictions')
    op.drop_table('sales_predictions')
    op.drop_index('idx_sale_item_sale', table_name='sale_items')
    op.drop_index('idx_sale_item_product', table_name='sale_items')
    op.drop_table('sale_items')
    op.drop_index('idx_reorder_status', table_name='reorder_suggestions')
    op.drop_index('idx_reorder_product', table_name='reorder_suggestions')
    op.drop_index('idx_reorder_priority', table_name='reorder_suggestions')
    op.drop_index('idx_reorder_business', table_name='reorder_suggestions')
    op.drop_table('reorder_suggestions')
    op.drop_index('idx_receipt_po', table_name='purchase_receipts')
    op.drop_index('idx_receipt_number', table_name='purchase_receipts')
    op.drop_table('purchase_receipts')
    op.drop_index('idx_po_item_product', table_name='purchase_order_items')
    op.drop_index('idx_po_item_po', table_name='purchase_order_items')
    op.drop_table('purchase_order_items')
    op.drop_index('idx_price_history_product', table_name='price_history')
    op.drop_index('idx_price_history_created', table_name='price_history')
    op.drop_table('price_history')
    op.drop_index('idx_inv_count_item_product', table_name='inventory_count_items')
    op.drop_index('idx_inv_count_item_count', table_name='inventory_count_items')
    op.drop_table('inventory_count_items')
    op.drop_index('idx_user_store_user', table_name='user_stores')
    op.drop_index('idx_user_store_store', table_name='user_stores')
    op.drop_table('user_stores')
    op.drop_index('idx_sale_store', table_name='sales')
    op.drop_index('idx_sale_payment', table_name='sales')
    op.drop_index('idx_sale_invoice', table_name='sales')
    op.drop_index('idx_sale_date', table_name='sales')
    op.drop_index('idx_sale_customer', table_name='sales')
    op.drop_index('idx_sale_business', table_name='sales')
    op.drop_table('sales')
    op.drop_index('idx_po_supplier', table_name='purchase_orders')
    op.drop_index('idx_po_status', table_name='purchase_orders')
    op.drop_index('idx_po_number', table_name='purchase_orders')
    op.drop_index('idx_po_business', table_name='purchase_orders')
    op.drop_table('purchase_orders')
    op.drop_index('idx_product_store', table_name='products')
    op.drop_index('idx_product_status', table_name='products')
    op.drop_index('idx_product_sku', table_name='products')
    op.drop_index('idx_product_expiry', table_name='products')
    op.drop_index('idx_product_category', table_name='products')
    op.drop_index('idx_product_business', table_name='products')
    op.drop_index('idx_product_barcode', table_name='products')
    op.drop_table('products')
    op.drop_index('idx_inv_count_store', table_name='inventory_counts')
    op.drop_index('idx_inv_count_number', table_name='inventory_counts')
    op.drop_index('idx_inv_count_business', table_name='inventory_counts')
    op.drop_table('inventory_counts')
    op.drop_index('idx_user_role', table_name='users')
    op.drop_index('idx_user_email', table_name='users')
    op.drop_index('idx_user_business', table_name='users')
    op.drop_table('users')
    op.drop_index('idx_supplier_name', table_name='suppliers')
    op.drop_index('idx_supplier_business', table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_index('idx_store_name', table_name='stores')
    op.drop_index('idx_store_business', table_name='stores')
    op.drop_table('stores')
    op.drop_index('idx_category_parent', table_name='categories')
    op.drop_index('idx_category_business', table_name='categories')
    op.drop_table('categories')
    op.drop_index('idx_business_email', table_name='businesses')
    op.drop_index('idx_business_created', table_name='businesses')
    op.drop_table('businesses')
    # ### end Alembic commands ###
